### ISSUE TITLE
Briefing Addons/A-10C CDU Wind - Magnetic Variation Not Used?

### ISSUE THREAD

**Issue by ValokAsura** [chump29/DCS_Mod#1]
Hello! I'm a DCS newb that stumbled upon your scripts and I'm wondering about the functionality of the A-10C CDU Wind calculator.

It doesn't seem to be taking the magnetic variation into account when updating the briefing screen. I've been trying to figure out how to add it myself but haven't managed to figure it out. It shows the variation in the briefing between QNH and Cloud Base, but doesn't figure it into the calculation for the CDU.

If you could take a look at it, I would greatly appreciate it. If it is just user-error on my part, feel free to let me know and delete this issue.

Thank you!

**Comment by chump29** [comment]
Thank you for bringing this to my attention. I have corrected the CDU wind to include the magVar. Please get the latest release version (v1.1.2). Let me know if you have any questions. Thanks

**Comment by ValokAsura** [comment]
I've updated and it looks good. Thank you very much!
